### ISSUE TITLE
Error during the launch for download after new update 0.3.2

### ISSUE THREAD

**Issue by pankaj151** [webtorrent/webtorrent-cli#100]
Hi, was just trying to download on my remote console, after hitting the following command.
COMMAND:sudo webtorrent download "622AEC26133440960B78AADD680734AE863CC6CD"
but on my another computer, which has version:0.103.1 was working fine.

DEBUG INFO: webtorrent-cli 1.12.3, webtorrent 0.103.2, node v8.16.0, linux x64, exit 1
/usr/lib/node_modules/webtorrent-cli/bin/cmd.js:399
    .on('error', function (err) {
    ^
TypeError: Cannot read property 'on' of undefined
    at runDownload (/usr/lib/node_modules/webtorrent-cli/bin/cmd.js:399:5)
    at /usr/lib/node_modules/webtorrent-cli/bin/cmd.js:187:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/lib/node_modules/webtorrent-cli/bin/cmd.js:186:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

**Comment by tryzniak** [comment]
Same's happening here. Rolling back to `webtorrent@0.103.1` fixes the issue. 
related to #101

**Comment by DiegoRBaquero** [comment]
Let's keep #101
