### ISSUE TITLE
Failed to download magnet link on Ubuntu

### ISSUE THREAD

**Issue by Lyken17** [webtorrent/webtorrent-cli#102]
OS: Ubuntu 18.04

``` bash
➜  torrban nodejs --version
v12.4.0
➜  torrban webtorrent --version
1.12.3 (0.103.2)
➜  torrban webtorrent download "magnet:?xt=urn:btih:bcb7b82d324b77298f353abfec328fc61e8dc6e0&dn=Bokutachi+wa+Benkyou+ga+Dekinai+11+%5BD83508CB%5D.mp4&tr=http%3A%2F%2F208.67.16.113%3A8000%2Fannounce&tr=http%3A%2F%2F61.154.116.205%3A8000%2Fannounce&tr=http%3A%2F%2Fbt.rghost.net%3A80%2Fannounce&tr=http%3A%2F%2Fbt.sc-ol.com%3A2710%2Fannounce&tr=http%3A%2F%2Fopen.acgtracker.com%3A1096%2Fannounce&tr=http%3A%2F%2Fopen.nyaatorrents.info%3A6544%2Fannounce&tr=http%3A%2F%2Fshare.camoe.cn%3A8080%2Fannounce&tr=http%3A%2F%2Ft2.popgo.org%3A7456%2Fannonce&tr=http%3A%2F%2Ftr.bangumi.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.ktxp.com%3A6868%2Fannounce&tr=http%3A%2F%2Ftracker.ktxp.com%3A7070%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.prq.to%2Fannounce&tr=http%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=https%3A%2F%2Ftr.bangumi.moe%3A9696%2Fannounce&tr=udp%3A%2F%2F208.67.16.113%3A8000%2Fannounce&tr=udp%3A%2F%2Ftr.bangumi.moe%3A6969%2Fannounce&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.12.3, webtorrent 0.103.2, node v12.4.0, linux x64, exit 1
/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:399
    .on('error', function (err) {
    ^

TypeError: Cannot read property 'on' of undefined
    at runDownload (/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:399:5)
    at /usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:187:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:186:14)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

Could you advise how I can fix the bug?

**Comment by Lyken17** [comment]
After pulling the latest code and run, I get following errors

```
ebtorrent 'magnet:?xt=urn:btih:bcb7b82d324b77298f353abfec328fc61e8dc6e0&dn=Bokutachi+wa+Benkyou+ga+Dekinai+11+%5BD83508CB%5D.mp4&tr=http%3A%2F%2F208.67.16.113%3A8000%2Fannounce&tr=http%3A%2F%2F61.154.116.205%3A8000%2Fannounce&tr=http%3A%2F%2Fbt.rghost.net%3A80%2Fannounce&tr=http%3A%2F%2Fbt.sc-ol.com%3A2710%2Fannounce&tr=http%3A%2F%2Fopen.acgtracker.com%3A1096%2Fannounce&tr=http%3A%2F%2Fopen.nyaatorrents.info%3A6544%2Fannounce&tr=http%3A%2F%2Fshare.camoe.cn%3A8080%2Fannounce&tr=http%3A%2F%2Ft2.popgo.org%3A7456%2Fannonce&tr=http%3A%2F%2Ftr.bangumi.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.ktxp.com%3A6868%2Fannounce&tr=http%3A%2F%2Ftracker.ktxp.com%3A7070%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.prq.to%2Fannounce&tr=http%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=https%3A%2F%2Ftr.bangumi.moe%3A9696%2Fannounce&tr=udp%3A%2F%2F208.67.16.113%3A8000%2Fannounce&tr=udp%3A%2F%2Ftr.bangumi.moe%3A6969%2Fannounce&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com'
/home/ligeng/webtorrent-cli/node_modules/opn/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ligeng/webtorrent-cli/bin/cmd.js:15:13)
```

**Comment by rom1504** [comment]
Install a recent node

**Comment by Lyken17** [comment]
@rom1504 Thanks for your suggestion. But I am already using the latest verion on https://nodejs.org/en/, which is v12.4.0

**Comment by Lyken17** [comment]
Can you share your nodejs version?

**Comment by DiegoRBaquero** [comment]
Original error is https://github.com/webtorrent/webtorrent-cli/issues/101 let's continue there

async one is node version.
