### ISSUE TITLE
Fails to play DLNA 

### ISSUE THREAD

**Issue by bumjrah** [webtorrent/webtorrent-cli#133]
Pass the command together with "--dlna" option at the end. Web-torrent quits. Weird enough, dlna client automatically opens up the default video app in an attempt to play the request. Debug error message attached

DEBUG INFO: webtorrent-cli 3.0.5, webtorrent 0.108.1, node v13.13.0, linux x64, exit 1
_http_outgoing.js:535
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:535:11)
    at Server.onRequest (/usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/server.js:87:9)
    at Server.emit (events.js:327:22)
    at parserOnIncoming (_http_server.js:779:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17) {
  code: 'ERR_HTTP_HEADERS_SENT'

**Comment by feross** [comment]
I can't reproduce this error and from looking at the code, I can't see how it would ever occur. If you think this is still an issue, please leave a comment, ideally with the exact command you used to invoke `webtorrent-cli`.
