### ISSUE TITLE
ENOENT ascii-logo.txt

### ISSUE THREAD

**Issue by IdanAdar** [webtorrent/webtorrent-cli#180]
Getting the following with a fresh install:

```
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 3.5.2, webtorrent 1.2.4, node v14.17.3, darwin x64, exit 1
internal/fs/utils.js:314
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/iadar/.nvm/versions/node/v14.17.3/lib/node_modules/webtorrent-cli/bin/ascii-logo.txt'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (/Users/iadar/.nvm/versions/node/v14.17.3/lib/node_modules/webtorrent-cli/bin/cmd.js:117:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/iadar/.nvm/versions/node/v14.17.3/lib/node_modules/webtorrent-cli/bin/ascii-logo.txt'
```

**Comment by OsmanAltun** [comment]
Also happens with version 3.5.1

**Comment by IdanAdar** [comment]
@DiegoRBaquero vsn you approve and merge fix?
