### ISSUE TITLE
error importing module chalk

### ISSUE THREAD

**Issue by zeldoon** [webtorrent/webtorrent-cli#208]
**What version of this package are you using?**
just cloned today 1/2/22

**What operating system, Node.js, and npm version?**
linux mint, node.js = v10.19.0, npm = v 6.14.4

**What happened?**
tried to launch webtorrent-cli in bash via webtorrent command

**What did you expect to happen?**
webtorrent to open

**Are you willing to submit a pull request to fix this bug?**
sure

console error:
$ webtorrent --help

/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:2
import chalk from 'chalk'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by DiegoRBaquero** [comment]
Requires Node 14+

Diego

**Comment by zeldoon** [comment]
urg... for anyone else seeing this; don't bother with mint's repo as it only goes up to v10 for node.js. Hop over here to get the latest version.

TY Diego
