### ISSUE TITLE
RangeError: offset out of bounds

### ISSUE THREAD

**Issue by CyberShadow** [webtorrent/webtorrent-cli#41]
```
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.10.1, webtorrent 0.98.18, node v8.3.0, linux x64, exit 1
fs.js:708
    return binding.writeBuffer(fd, buffer, offset, length, position, req);
                   ^

RangeError: offset out of bounds
    at Object.fs.write (fs.js:708:20)
    at onwrite (/home/vladimir/.npm-packages/lib/node_modules/webtorrent-cli/node_modules/random-access-file/index.js:187:8)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:691:5)
```

Torrent is [REDACTED]

Crash occurred while playing file 0 with mpv.

**Comment by CyberShadow** [comment]
> Crash occurred while playing file 0 with mpv.

Streaming to a player has nothing to do with it; `webtorrent-cli` consistently fails to finish downloading the torrent without a player running.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
