### ISSUE TITLE
Buffer.alloc is not a function on ubuntu 16.04

### ISSUE THREAD

**Issue by FinnFrotscher** [webtorrent/webtorrent-cli#47]
cant run webtorrent on ubuntu 16.04
```
root@vps383796:/home# webtorrent xyz
/usr/local/lib/node_modules/webtorrent-cli/node_modules/parse-torrent/index.js:110
;(function () { Buffer.alloc(0) })()
                       ^

TypeError: Buffer.alloc is not a function
    at /usr/local/lib/node_modules/webtorrent-cli/node_modules/parse-torrent/index.js:110:24
    at Object.<anonymous> (/usr/local/lib/node_modules/webtorrent-cli/node_modules/parse-torrent/index.js:110:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:16:20)
    at Module._compile (module.js:410:26)

                       ^

```

**Comment by rom1504** [comment]
you need a more recent node

**Comment by FinnFrotscher** [comment]
fixed it
